spring:
  datasource:
    username: postgres
    password: 1
    url: jdbc:postgresql://localhost:5432/property-management
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
server:
  port: 8080
stripe:
  public:
    key: pk_test_51L0IFfLni6USJ4Eno3RofGbEBYWBPups7yaZ9K0zDEV36mBw2FALfjvMHkGQQgqZG2BYQCwH65Z7xS178LGFxTqx00KaLYLpD3
  secret:
    key: sk_test_51L0IFfLni6USJ4En1glDlYDg31ppBozga0EhmsEHDNDdqCkoby9wDsQgu6giIZjo3D5IFHc0QgPXjtlabtGRIgLy00640RkSlj

